CREATE TABLE INSTRUCTOR(
   ID_INSTRUCTOR NUMERIC(10,0) NOT NULL PRIMARY KEY,
   APELLIDO_PATERNO varchar2(60) NOT NULL,
   APELLIDO_MATERNO varchar2(60) NOT NULL,
   NOMBRES varchar2(60) NOT NULL,
   SEXO char(1) NOT NULL,
   ID_TIPO_DOCUMENTO NUMERIC(2,0) NOT NULL REFERENCES TIPO_DOCUMENTO(ID_TIPO_DOCUMENTO),
   NRO_DOCUMENTO varchar2(20) NOT NULL,
   CORREO varchar2(20)  NULL,
   TELEFONO varchar2(20)  NULL,
   FECHA_INGRESO DATE  NULL ,   
   ESTADO char(1) DEFAULT '1'
);

CREATE SEQUENCE SEQ_INSTRUCTOR;

INSERT INTO INSTRUCTOR(ID_INSTRUCTOR,APELLIDO_PATERNO,APELLIDO_MATERNO,NOMBRES,SEXO,ID_TIPO_DOCUMENTO,NRO_DOCUMENTO)
VALUES(SEQ_INSTRUCTOR.NEXTVAL,'NOVOA','ARBILDO','ARISTEDES','M',1,'10611698');
INSERT INTO INSTRUCTOR(ID_INSTRUCTOR,APELLIDO_PATERNO,APELLIDO_MATERNO,NOMBRES,SEXO,ID_TIPO_DOCUMENTO,NRO_DOCUMENTO)
VALUES(SEQ_INSTRUCTOR.NEXTVAL,'MAMANI','LORD','MARTHA','F',1,'40611698');
INSERT INTO INSTRUCTOR(ID_INSTRUCTOR,APELLIDO_PATERNO,APELLIDO_MATERNO,NOMBRES,SEXO,ID_TIPO_DOCUMENTO,NRO_DOCUMENTO)
VALUES(SEQ_INSTRUCTOR.NEXTVAL,'MAMANI','GOMEZ','JULIO','M',2,'001043328');

COMMIT;

SELECT ID_INSTRUCTOR,APELLIDO_PATERNO,APELLIDO_MATERNO,NOMBRES,SEXO,ID_TIPO_DOCUMENTO,NRO_DOCUMENTO FROM INSTRUCTOR
